version: '3.6'
services:
  nightfall_dlp_build:
    image: builder
    build:
      context: .
      target: builder
      args:
        - GIT_USER=${GIT_USER:-engbot}
        - GIT_PASS=${GIT_PASS}
    environment:
      GO_ENV: ci
    command: ./nightfall_dlp

  wait:
    image: deliveroo/circleci:0.2.8
